export const SCROLL_STATE = "SCROLL_STATE";
export const RANDOM_SCROLL = "RANDOM_SCROLL";
export const CATEGORY_STATE = "CATEGORY_STATE";
export const CATEGORY_POST = "CATEGORY_POST";
export const INSIDE_CATEGORY = "INSIDE_CATEGORY";